name: aoe_ranking
description: Bảng xếp hạng ELO nội bộ team AoE (đọc data/leaderboard.json).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
